### ISSUE TITLE
Create widget variations

### ISSUE THREAD

**Issue by charlieyouakim** [sezzle/sezzle-js#113]
We'd like to create a short variation:

"or 4 payments with Sezzle"

So let's create a system for this where we can create multiple variations and log the results

varStandard: what we have
varShort: "or 4 payments with <Sezzle Logo>"
varShort2: "another short option"
varAlt: "yada yada"
varAlt2: "yada yada 2"

Don't worry about the variations here - just make sure it can support the short variation given as an example and then create the system around more variations.

**Comment by killianbrackey** [comment]
We chatted about this again and decided it would be a good idea to make the text an input as a templated string.  We could utilize {% %} or something similar with names for the amount and logo and allow the implementer to set those within a string and make it work nicely on the site.

Thoughts @ibremseth @charlieyouakim @rishimukherjee
