### ISSUE TITLE
Sezzle woocommerce wordpress plugin is not working. Any helps ?

### ISSUE THREAD

**Issue by ashishkatoch** [sezzle/sezzle-js#228]
I am getting an error in checkout. I have used proper configuration of public/private key. Also setup merchant id.

I have not setup yet bank account. Is it required to setup bank account ?

Thanks

**Comment by rishimukherjee** [comment]
Hi Ashish,

What is the error you see in checkout? Also, can you help with the logs?

Thanks,
Rishi
