### ISSUE TITLE
Attach to div not working on Freddystore.com

### ISSUE THREAD

**Issue by charlieyouakim** [sezzle/sezzle-js#32]
Sudipta - can you please take a look? We wanted to try your code on freddystore.com but it didn't work there.

Thank you!

**Comment by killianbrackey** [comment]
Attempted configuration:
```document.sezzleConfig = {
    targetXPath: ['#price-preview/.money'],
	renderToPath: ['.add_product_btn'],
    forcedShow: false,
    alignment: 'left',
    merchantID: '1',
    theme: 'light',
    widthType: 'thin',
    widgetType: 'product-page',
    minPrice: 0,
    maxPrice: 100000,
    imageUrl: ''
  };```

**Comment by sanbornsen** [comment]
If you want to place it under the button, this should be the correct path 

```renderToPath: ['./../../../../.buttons-add-product']```

**Comment by charlieyouakim** [comment]
Wow that's one hell of a path!

**Comment by sanbornsen** [comment]
The path is always respective to the price element. One thing is not done is, how to place the widget in the middle of the div. Now we are placing at the end of the target element.

**Comment by sanbornsen** [comment]
```renderToPath: ['./../..']```
for 
<img width="616" alt="screen shot 2017-10-11 at 8 08 14 am" src="https://user-images.githubusercontent.com/2410474/31419816-875856ae-ae5b-11e7-90ca-03a074ac2ab4.png">

```renderToPath: ['./../../../.buttons-add-product'],```
for 
<img width="631" alt="screen shot 2017-10-11 at 8 08 26 am" src="https://user-images.githubusercontent.com/2410474/31419835-9ebeb81a-ae5b-11e7-9098-90ce11f4ac49.png">

**Comment by rishimukherjee** [comment]
I think we should it in a way such that the render to path is just an xpath instead of a relative path.

**Comment by sanbornsen** [comment]
Do you mean x-path like the one we have for **targetXPath** , well we can have it like that, but then what are the pros and cons ?
