### ISSUE TITLE
Price Range Split Character

### ISSUE THREAD

**Issue by killianbrackey** [sezzle/sezzle-js#404]
Adding a new parameter for splitting a range of prices that have the same price elements as a configuration item would allow sites like https://thelaurenashtyncollection.com/product/adrianna-light-volume/ (generally woocommerce) to have a config like: 
```javascript
document.sezzleConfig = {
  "targetXPath": [
    ".price"
  ],
  "renderToPath": [
    "."
  ],
  "forcedShow": false,
  "alignment": "left",
  "merchantID": "merchant_uuid",
  "theme": "dark",
  "widthType": "thick",
  "widgetType": "product-page",
  "minPrice": 0,
  "maxPrice": 100000,
  "imageUrl": "",
  "hideClasses": [
    ""
  ]
}
```

and give the range with the split items divided by 4

**Comment by jan-wei** [comment]
https://github.com/sezzle/sezzle-js/pull/405
