### ISSUE TITLE
A/B test two new versions of the modal - split 50/50 and track conversions (signup)

### ISSUE THREAD

**Issue by miamiabernad** [sezzle/sezzle-js#573]
Implement two new versions of the modal and A/B test them for checkout initiations. 

https://scene.zeplin.io/project/5cb8754e2069be0a3e1e8d5c

@MartaJopp

**Comment by hardikk08** [comment]
Have implemented all the designs. Here is the pull request - https://github.com/sezzle/sezzle-js/pull/587
