### ISSUE TITLE
Expose method to re-render widget

### ISSUE THREAD

**Issue by stewartknapman** [sezzle/sezzle-js#820]
We are installing the Sezzle widget on a headless Shopify site that is built on React.
The way React re-renders components breaks the widgets mutation observer and means that the widget won't update if the products/variants price changes. Noted in this issue: https://github.com/sezzle/sezzle-js/issues/476

It would be great to be able to call a global re-render method manually in this case to force it to update the price.

**Comment by ucjonathan** [comment]
We need this as well.  We're adding Sezzle as a "widget" to our visual builder and often times the element will repaint, but we have no way to tell Sezzle to redraw itself.

**Comment by aholdahl** [comment]
Sezzle offers a separate widget version for React websites, which is available as an NPM package. Use the command `npm install sezzle-react-widget`, import the component to the code file, and pass props. {price} and {merchantId} are required.

**Comment by ucjonathan** [comment]
We are not a React based site.  We are integrating your widget within a jQuery site that does some dynamic rendering.  Please expose a method.

**Comment by aholdahl** [comment]
For JQuery, sometimes adjusting the targetXPath can do the trick, as the mutation observer doesn't catch all changes. If you submit a ticket to merchantsupport@sezzle.com with the shop URL, Sezzle widget team can take a look and either advise or do the config for you (it saves to our server and is retrieved by the script).

We also offer a [static widget](https://github.com/sezzle/static-widgets) product, which sits entirely in the shop's theme and allows for a custom event listener.
