### ISSUE TITLE
React Library out of date

### ISSUE THREAD

**Issue by alexcastillo** [sezzle/sezzle-js#848]
Hi!

Thank you so much for this project!

I noticed the [sezzle-react-widget](https://www.npmjs.com/package/sezzle-react-widget) npm package is out o date. The contract between the native web widget and this library is no longer in sync.

For example:
 - Some properties are not supported
 - Some properties have been renamed
 - The logos are the old Sezzle logos
 - Themes are incomplete

I noticed the library is not open source. Are there plans to update the Sezzle react library?

Thank you!

**Comment by aholdahl** [comment]
Sorry for not responding here - we released some updates a couple weeks ago. Please be sure to follow the instructions on the React README in NPM - implementation is different for that version than this one.

**Comment by alexcastillo** [comment]
Thank you!

Any plans to open source the React library? Since there's no change log, I'd like to be able to see what has changed via commits.
