### ISSUE TITLE
Add styling as an array too

### ISSUE THREAD

**Issue by charlieyouakim** [sezzle/sezzle-js#87]
Just added the widgets to barklyn grace. The widgets need to be styled differently for the multiple locations.

See Screenshots:
<img width="1429" alt="screen shot 2017-11-09 at 8 32 28 am" src="https://user-images.githubusercontent.com/991225/32610482-8d2c8242-c528-11e7-9a64-d7b919919002.png">
<img width="1439" alt="screen shot 2017-11-09 at 8 32 21 am" src="https://user-images.githubusercontent.com/991225/32610483-8d3e4f68-c528-11e7-8deb-b84e4369a1c8.png">

**Comment by charlieyouakim** [comment]
@sanbornsen can you help 🙏

**Comment by killianbrackey** [comment]
I think this is already fixed if you just add a different type to the other widget (say `cart`) you can write the specific CSS override for this site on that type of widget.
